language: go

go:
  - master

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE lxd_testing;' -U postgres
  - cp config/testing.example.yaml config/testing.yaml

script:
  - go test -v ./...
