language: go

go :
  - "1.10.3"

services:
  - postgresql

install: true

before_script:
  - go get github.com/Masterminds/glide
  - glide install

script:
  - go clean -testcache
  - go test -v -race ./...
